# Use root/example as user/password credentials

version: '3.1'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    external_links:
      - db:db
    ports:
      - 8081:80

  db:
    image: mysql:5.6
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306
